### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AllexVeldman** [AllexVeldman/learn-python#1]
- [ ] Generic programming intro
- [ ] What does python do/add
- [ ] make difference interpreter and compiler clear
- [ ] Describe in jip-en-janeke what function-scope is, opdelen lange stukken code is herbruikbare/behapbare stukjes code
- [ ] after "optellen" assignment: calculate surface of square
- [ ] if-statements
- [ ] loops
- [ ] Add example usage of list and dicts
- [ ] sets
- [ ] [Pitfalls] mutable defaults
- [ ] separation between what is user-defined (variables/functions) and what is provided (builtins/imports) is not clear, switch example code to dutch or other non-english language
- [ ] consistent use of terms, use dictionary instead of key-value pairs
